package euler;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be: 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
public class Two {

	public static double two(){
		final int LIMIT = 4000000;
		
		double prev = 1;
		double head = 2;
		
		double sum = 2;
		
		while(true){
			double temp = head;
			head = head + prev; 
			prev = temp;
			
			if(head>LIMIT){
				break;
			}
			else if(head%2==0){
				sum+=head;
			}
		}
		
		return sum;
	}
	
	public static void main(String... args){
		System.out.println(two());
	}
}
